# Generated by Django 5.2.9 on 2026-04-01 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_finanzas', '0006_remove_finanza_tipo_nuevo_finanza_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='finanza',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_mensualidad', to=settings.AUTH_USER_MODEL, verbose_name='Socio/Transportista'),
        ),
    ]
