# Generated by Django 5.2.9 on 2026-04-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_finanzas', '0007_finanza_socio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_implementacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_implementacion'],
            },
        ),
    ]
